### ISSUE TITLE
Anvil 0.2.0 Support

### ISSUE THREAD

**Issue by brianegan** [trikita/anvil-recyclerview#1]
Heyo! Just tried this out last night for the first time. Thanks for providing RecyclerView support! Really great for things like Animations.

However, I originally tried this lib out with Anvil 0.2.0 and it didn't work, then downgraded to 0.1.2 and it worked fine. Didn't have time to determine the exact cause, but I believe the problem originated from `RenderableRecyclerViewAdapter` line 22. Thanks!

**Comment by brianegan** [comment]
Dump of the error log I was encountering:

```
01-30 07:35:56.231 13866-13866/trikita.anvil.recycle.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: trikita.anvil.recycle.example, PID: 13866
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void trikita.anvil.Anvil$Mount.startFromClass(java.lang.Class)' on a null object reference
                                                                                   at trikita.anvil.BaseDSL.v(BaseDSL.java:512)
                                                                                   at trikita.anvil.BaseDSL.v(BaseDSL.java:530)
                                                                                   at trikita.anvil.DSL.textView(DSL.java:676)
                                                                                   at trikita.anvil.recycle.example.RecyclerViewExample$SimpleList.lambda$null$1(RecyclerViewExample.java:43)
                                                                                   at trikita.anvil.recycle.example.RecyclerViewExample$SimpleList.access$lambda$1(RecyclerViewExample.java)
                                                                                   at trikita.anvil.recycle.example.RecyclerViewExample$SimpleList$$Lambda$4.view(Unknown Source)
                                                                                   at trikita.anvil.recyclerview.Recycler$Adapter$1.view(Recycler.java:117)
                                                                                   at trikita.anvil.RenderableRecyclerViewAdapter$1.view(RenderableRecyclerViewAdapter.java:24)
                                                                                   at trikita.anvil.Anvil$Mount.render(Anvil.java:204)
                                                                                   at trikita.anvil.RenderableRecyclerViewAdapter.onBindViewHolder(RenderableRecyclerViewAdapter.java:27)
                                                                                   at trikita.anvil.RenderableRecyclerViewAdapter.onBindViewHolder(RenderableRecyclerViewAdapter.java:7)
                                                                                   at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
                                                                                   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                                   at android.view.View.layout(View.java:16630)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at android.view.View.layout(View.java:16630)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at android.view.View.layout(View.java:16630)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                   at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
                                                                                   at android.view.View.layout(View.java:16630)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                   at android.view.View.layout(View.java:16630)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(Zyg
```

**Comment by brianegan** [comment]
I've taken a look at the problem, and found the root cause. I'll be submitting a PR as a fix to this problem shortly!
